<?php
/**
 * @var \Absoft\WallCatalog\Block\Index $block
 * @var \Magento\Catalog\Api\Data\ProductInterface $product
 * @var \Magento\Catalog\Api\Data\ProductCustomOptionInterface $option
 */
//$_product = $block->getProduct();
$_productColection = $block->getProductByAttributeSet();
?>
<input type="hidden" id="product_sku" value="<?= $block->getSku() ?>">
<?php foreach ($_productColection->getItems() as $product) { ?>
    <div class="app" id="app">
            <h1 style="text-align: center"><?= $product->getName() ?></h1>

        <form action="<?= $block->getUrl('wallcatalog/index/preview',['sku'=>$product->getSku()]) ?>" class="preview-form">
            <div class="fieldset">
                <?php foreach ($block->getProductOptions($product) as $option) { ?>
                    <?php if ($option->getTitle() != 'Width' && $option->getTitle() != 'Height'): ?>
                    <div class="field required">

                        <label class="label" for="<?= $option->getOptionId() ?>"><?= $option->getTitle() ?></label>
                        <?php if ($option->getType() == 'field'): ?>

                            <input class="input-text" id="<?= $option->getOptionId() ?>"
                                   name="<?= $option->getOptionId() ?>" data-validate="{required:true}">
                        <?php elseif ($option->getType() == 'drop_down'): ?>
                            <select id="<?= $option->getOptionId() ?>" name="<?= $option->getOptionId() ?>">
                                <?php foreach ($option->getValues() as $index => $value):
                                    echo "<option value='{$value['option_type_id']}'>{$value['title']}</option>";
                                endforeach; ?>
                            </select>
                        <?php endif; ?>
                    </div>
                    <?php endif; ?>
                <?php } ?>

            </div>
            <div class="product-item">
                <input type="submit" class="action tocart primary" value="Preview">
            </div>
        </form>
    </div>

<?php } ?>

<script type="text/x-magento-init">
    {
        ".preview-form": {
            "validation": {}
        }
    }
</script>

<style>

    .app {
        float: left;
        padding: 15px;
        margin-right: 65px;
        margin-bottom: 100px;
        width: 25%;
        -webkit-box-shadow: 3px 3px 5px 4px rgba(0, 0, 0, 0.31);
        -moz-box-shadow: 3px 3px 5px 4px rgba(0, 0, 0, 0.31);
        box-shadow: 3px 3px 5px 4px rgba(0, 0, 0, 0.31);
    }
    .input-text {
        background: #fff;
        background-clip: padding-box;
        border: 1px solid #c2c2c2;
        border-radius: 1px;
        font-family: 'Open Sans','Helvetica Neue',Helvetica,Arial,sans-serif;
        font-size: 14px;
        height: 32px;
        line-height: 1.42857143;
        padding: 0 9px;
        vertical-align: baseline;
        width: 100%;
        box-sizing: border-box;
    }
</style>