<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Absoft\WallCatalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php $view = __('Preview'); ?>

<?php if ($_product->isSaleable()): ?>
    <div class="box-tocart">
        <div class="fieldset">
            <?php if ($block->shouldRenderQuantity()): ?>
                <div class="field qty">
                    <label class="label" for="qty"><span><?= /* @escapeNotVerified */ __('Qty') ?></span></label>
                    <div class="control">
                        <input type="number"
                               name="qty"
                               id="qty"
                               value="<?= /* @escapeNotVerified */ $block->getProductDefaultQty() * 1 ?>"
                               title="<?= /* @escapeNotVerified */ __('Qty') ?>"
                               class="input-text qty"
                               data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                        />
                    </div>
                </div>
            <?php endif; ?>
            <div class="actions">
                <button type="submit"
                        title="<?= /* @escapeNotVerified */ $buttonTitle ?>"
                        class="action primary tocart"
                        id="product-addtocart-button">
                    <span><?= /* @escapeNotVerified */ $buttonTitle ?></span>
                </button>
                <?php if($_product->getAllowPreview()): ?>
                <input type="hidden" name="sku" value="<?= $_product->getSku()?>">
                <input type="hidden" name="cartId" value="<?= $block->getCartMaskId()?>">
                <input type="hidden" name="productType" value="<?= $_product->getWallcatalogType()?>">
                <button type="button"
                        title="<?= /* @escapeNotVerified */ $view ?>"
                        class="action default tocart"
                        id="preview">
                    <span><?= /* @escapeNotVerified */ $view ?></span>
                </button>
                <?php endif; ?>
                <?= $block->getChildHtml('', true) ?>
            </div>
        </div>
    </div>
<?php endif; ?>

<?php if($_product->getAllowPreview()): ?>
<script type="text/javascript">
    require([
        'jquery',
        'mage/validation'
    ], function($){

        var dataForm = $('#product_addtocart_form');
        dataForm.mage('validation', {})
//        var ignore = null;
//
//        dataForm.mage('validation', {
//            ignore: ignore ? ':hidden:not(' + ignore + ')' : ':hidden'
//        }).find('input:text').attr('autocomplete', 'off');

        $('#preview').click(function(){
//            var dataForm = $(this).closest('form');

//            dataForm.mage('validation', {})

            var isValid = dataForm.validation('isValid');
            var form = $(this).closest('form');
            var data_form = form.serializeArray();
            var result =[].reduce.call(data_form,function(last,data){
                if(data.name.search('options')!=-1){
                    var regex = /\d+/g;
                    var index = data.name.match(regex)
                    last[index] = data.value
                }
                if(data.name== 'qty'||data.name=='sku' || data.name=='cartId' || data.name=='productType'){
                    last[data.name] = data.value
                }
                return last;
            },{})
            if(isValid){
                location.href = 'http://wallcatalog.local/?'+$.param(result)
            }
        })

    });
</script>
<?php endif; ?>
<?php if ($block->isRedirectToCartEnabled()) : ?>
    <script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/product/view/validation": {
                "radioCheckboxClosest": ".nested"
            }
        }
    }
</script>
<?php else : ?>
    <script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }
</script>
<?php endif; ?>
