<?php
/**
 * @var \Absoft\WallCatalog\Block\Preview $block
 * @var \Magento\Catalog\Api\Data\ProductInterface $product
 * @var \Magento\Catalog\Api\Data\ProductCustomOptionInterface $option
 */
$_product = $block->getProduct();
$_productColection = $block->getProductByAttributeSet();
$_options = $block->getOptions($_product->getSku());
?>
<!--<h1 style="text-align: center">JSON data for Product SKU: --><?php //$block->getSku() ?><!--</h1>-->
<input type="hidden" id="product_sku" value="<?= $block->getSku() ?>">

<div id="app">
    <h1 style="text-align: center"><?= $_product->getName() ?></h1>

    <div>
        <form ref="cartForm" v-on:submit.prevent="onSubmit">
            <div class="fieldset">
                <div class="field">
                    <label class="label" for=""><?= __("Cart ID") ?></label>
                    <input type="text" id="quoteIdMask" value="<?php echo $block->getQuoteIdMask() ?>">
                </div>

                <?php foreach ($block->getParams() as $index=> $value) {
                    foreach ($_options as $option) {
                        if($index==$option->getOptionId()){?>
                                <div class='field'>
                                    <label class='label'><?= $option->getTitle()?></label>
                            <?php if($option->getType()=='field'){?>
                                    <input type='text' value='<?= $value ?>' name='<?= $option->getTitle()=='Qty'?'qty':$index ?>'>
                            <?php }
                                if($option->getType()=='drop_down'){ ?>
                                    <select name="<?= $index?>">
                                        <?php foreach ($option->getValues() as $item) {?>
                                            <option value="<?= $value?>" <?= $item->getOptionTypeId()==$value?"selected":"" ?>><?= $item->getTitle()?></option>
                                        <?php }?>
                                    </select>
                                </div>
                                <?php
                            }
                        }
                    }
                } ?>
    </div>

    <?php foreach ($_options as $option) {
                if (!key_exists($option->getOptionId(), $block->getParams())) {
                    ?>
                    <div class="field">
                        <label for="" class="label"><?= $option->getTitle() ?></label>
                        <input type="text" name="<?= $option->getOptionId() ?>">
                    </div>
                    <?php
                }
            }
            ?>
            </div>
            <div class="product-item">
                <input type="submit" class="action tocart primary" value="Add To Cart">
            </div>

        </form>
    </div>
    <button v-on:click="check(cartForm)">CLick</button>
    <pre v-if="loadding==true">
        <img src="https://loading.io/spinners/microsoft/index.svg" alt="" style="margin: auto;display: block">
        <!--        <span v-else >{{ product | json }}</span>-->
    </pre>
</div>

<style>
    #app {
    padding: 15px;
    margin: 0 auto;
    width: 25%;
    -webkit-box-shadow: 3px 3px 5px 4px rgba(0, 0, 0, 0.31);
    -moz-box-shadow: 3px 3px 5px 4px rgba(0, 0, 0, 0.31);
    box-shadow: 3px 3px 5px 4px rgba(0, 0, 0, 0.31);
    }

    /*.app {*/
        /*float: left;*/
        /*padding: 15px;*/
        /*margin-right: 65px;*/
        /*margin-bottom: 100px;*/
        /*width: 25%;*/
        /*-webkit-box-shadow: 3px 3px 5px 4px rgba(0, 0, 0, 0.31);*/
        /*-moz-box-shadow: 3px 3px 5px 4px rgba(0, 0, 0, 0.31);*/
        /*box-shadow: 3px 3px 5px 4px rgba(0, 0, 0, 0.31);*/
    /*}*/
    /*.input-text {*/
        /*background: #fff;*/
        /*background-clip: padding-box;*/
        /*border: 1px solid #c2c2c2;*/
        /*border-radius: 1px;*/
        /*font-family: 'Open Sans','Helvetica Neue',Helvetica,Arial,sans-serif;*/
        /*font-size: 14px;*/
        /*height: 32px;*/
        /*line-height: 1.42857143;*/
        /*padding: 0 9px;*/
        /*vertical-align: baseline;*/
        /*width: 100%;*/
        /*box-sizing: border-box;*/
    /*}*/
</style>